### ISSUE TITLE
Time to port this to fonttools?

### ISSUE THREAD

**Issue by behdad** [khaledhosny/deotfy#1]

**Comment by khaledhosny** [comment]
Is anyone actually using/wanting it?

**Comment by behdad** [comment]
I know @twardoch asked for it a few times.  He even had a script himself.

Of course, we want to redo it to update cmap only.

**Comment by behdad** [comment]
I don't know if you saw this before, but the young man (highschooler!) who did this font:
https://github.com/Kelvinsong/swiftday/

also wrote some code to add OpenType features such that, in Inkscape and other apps that didn't support enabling OpenType features, you'd type "<scmp>abcd</scmp>" and that enables scmp feature for that range.  Really neat hack.

**Comment by khaledhosny** [comment]
OK, I think it can be rewritten on top of FontTools but I have no uses for it actually, so it is not a priority (I never had any use for it actually, it was written as an answer to a Typophile question, an answer that even got completely ignored).

**Comment by twardoch** [comment]
I’ve just published [pyftfeatfreeze](https://github.com/twardoch/fonttools-utils/), fontTools-based command-line tool to “freeze” some OpenType features into a font, so small caps, oldstyle numerals or localized forms become available in apps that don’t support OpenType Layout features (such as many office apps).
